{
 "title": "Vault",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Number of Leases",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.expire.num_leases",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"vault.expire.num_leases\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "target": "stats.gauges.vault.vaults0.consul.expire.num_leases"
    }
   ]
  },
  {
   "title": "Audit Request Fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.audit.log_request_failure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.vault.audit.log_request_failure"
    }
   ]
  },
  {
   "title": "Audit Response Fail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.audit.log_response_failure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.vault.audit.log_response_failure"
    }
   ]
  },
  {
   "title": "Barrier GET",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.barrier.get",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.timers.vault.barrier.get.median"
    }
   ]
  },
  {
   "title": "Barrier PUT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.barrier.put",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.timers.vault.barrier.put.median"
    }
   ]
  },
  {
   "title": "Rollback KV",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.rollback.attempt.kv-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.timers.vault.rollback.attempt.vaultron-kv-.count"
    }
   ]
  },
  {
   "title": "Check Token",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.core.check_token",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "target": "stats.timers.vault.core.check_token.median"
    }
   ]
  },
  {
   "title": "Vault Seal Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "check_id" ], "type": "tag" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "unsealed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" },
      { "condition": "AND", "key": "service_name", "operator": "=", "value": "vault" }
     ]
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.heap_objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.gauges.vault.vaults0.consul.runtime.heap_objects"
    }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.alloc_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.gauges.vault.vaults0.consul.runtime.alloc_bytes"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.sys_bytes",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.gauges.vault.vaults1.consul.runtime.alloc_bytes"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"total\") FROM \"autogen\".\"mem\" WHERE (\"role\" = 'vault-server') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.gauges.vault.vaults2.consul.runtime.alloc_bytes"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "User CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "System CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "IOWait CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Idle CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.gauges.vault.vaults0.consul.runtime.alloc_bytes"
    }
   ]
  },
  {
   "title": "WAL GC Delete",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.wal.gc.deleted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.gauges.vault.vaults0.consul.wal.gc.deleted"
    }
   ]
  },
  {
   "title": "Token Create",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.token.create",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.timers.vault.token.create.median"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.runtime.num_goroutines",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.gauges.vault.vaults0.consul.runtime.num_goroutines"
    }
   ]
  },
  {
   "title": "KV Creates/Reads/Updates/Lists",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.create.kv-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.read.kv-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.update.kv-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.list.kv-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    }
   ]
  },
  {
   "title": "Merkle SaveCheckpoint",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.merkle.saveCheckpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ],
     "target": "stats.timers.vault.merkle.saveCheckpoint.median"
    }
   ]
  },
  {
   "title": "Token Lookup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.token.lookup",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    }
   ]
  },
  {
   "title": "Secret Creates/Reads/Updates/Lists",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.create.secret-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.delete.secret-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.list.secret-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vault.route.update.secret-",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "vault-server" }
     ]
    }
   ]
  }
 ]
}